YandexMusicStat/urls.py
from django.contrib import admin
from django.urls import path
from main import views
from django.urls import path , include
from myauth.views import *
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('' , views.main_page_view , name='main-page'),
    path('admin/', admin.site.urls),
    path('login/' , include('myauth.urls')),
    path('logout/', logout_view, name='logout'),
    path('profile-token/', profileToken_view, name='profile-token'),
    path('profile/', redirect_to_profile_view),
    path('profile/user/<slug:username>/' , profile_view, name='profile'),
    path('profile/edit/', profile_edit_view, name='profile-edit'),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myauth/urls.py
from django.contrib import admin
from django.urls import path
from .views import *

urlpatterns = [
    path('', login_page_view,  name='auth-page'),
]

myauth/models.py
from django.contrib.auth.models import User
from django.db import models
from .utils import TokenEncryption

class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    avatar = models.ImageField(upload_to='avatars/%Y/%m/%d/', default="avatars/images.png" , null=True, blank=True,)
    encrypted_token = models.TextField(blank=True,null=True,verbose_name='encrypted_token')
    bio = models.TextField(null=True, blank=True,verbose_name='bio')
    hidden = models.BooleanField(default=False,verbose_name='hidden')
    created_at = models.DateTimeField(auto_now_add=True,verbose_name='date of creation')
    updated_at = models.DateTimeField(auto_now=True,verbose_name='date of update')

    class Meta:
        verbose_name = 'User Profile'
        verbose_name_plural = 'Users Profiles'

    def __str__(self):
        return f"Profile {self.user.username}"

    def save_token(self, token: str):
        """Сохраняет токен в зашифрованном виде"""
        encryptor = TokenEncryption()
        self.encrypted_token = encryptor.encrypt(token)
        self.save()

    def get_token(self) -> str:
        """Получает расшифрованный токен"""
        if not self.encrypted_token:
            return None
        encryptor = TokenEncryption()
        return encryptor.decrypt(self.encrypted_token)

    def has_token(self) -> bool:
        """Проверяет наличие токена"""
        return bool(self.encrypted_token)

myauth/forms.py
import email

from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User


class RegisterForm(forms.Form):
    username = forms.CharField(max_length=20, widget=forms.TextInput(attrs={
        'placeholder': 'Login',
    }))

    password = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Password',
    }), label="Пароль")

    email = forms.EmailField(widget=forms.EmailInput(attrs={
        'placeholder': 'Email',
    }))

class LoginForm(forms.Form):
    username = forms.CharField(max_length=20, widget=forms.TextInput(attrs={
            'placeholder': 'Login',
        }))
    password = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Password',
    }), label="Пароль")

class TokenForm(forms.Form):
    token = forms.CharField(max_length=100, widget=forms.TextInput(attrs={
        'placeholder': 'Token',
    }))

class UserForm(forms.Form):
    avatar = forms.ImageField(required=False)
    username = forms.CharField(required=False,max_length=20, widget=forms.TextInput(attrs={
        'class': 'form-control',
        'id': 'username',
    }))
    email = forms.EmailField(required=False,widget=forms.EmailInput(attrs={
        'class': 'form-control',
        'id': 'email',

    }))
    bio = forms.CharField(required=False,widget=forms.Textarea(attrs={
        'class': 'form-control',
        'id': 'bio',
    }))
    hidden = forms.BooleanField(required=False, widget=forms.CheckboxInput(attrs={

    }))

myauth/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from .forms import LoginForm, RegisterForm , TokenForm , UserForm
from yandex_music import Client


def login_page_view(request):
    if request.method == "POST":
        action = request.POST.get('action')
        if action == 'login':
            return login_view(request)
        elif action == 'register':
            return register_view(request)

    # GET запрос
    if request.user.is_authenticated:
        return redirect('profile-token')

    return render(request, 'myauth/Auth.html', {
        'form1': LoginForm(),
        'form2': RegisterForm()
    })

def profileToken_view(request):
    if request.method == "POST":
        print(request.POST)
        form = TokenForm(request.POST)
        if form.is_valid():
            try:
                Client(form.cleaned_data['token']).init()
            except:
                return render(request, 'myauth/profile-token.html', context={'form': form , 'error': True})
            user = request.user
            user.userprofile.save_token(form.cleaned_data['token'])
            return redirect('profile' , username=request.user.username)
        else:
            return render(request, 'myauth/profile-token.html', context={'form': form , 'error': True})

    if request.user.is_authenticated:
        if request.user.userprofile.has_token():
            return redirect('profile', username=request.user.username)
        form = TokenForm()
        return render(request, 'myauth/profile-token.html', {'form': form , 'user': request.user})
    else:
        return redirect('auth-page')

def profile_view(request , username):
    try:
        user = User.objects.get(username=username)
    except:
        return HttpResponse("Ops page not found")

    if request.user.username == username:
        if user.userprofile.has_token():
            token = user.userprofile.get_token()
            client = Client(token).init()
            liked_context = create_like_playlist(client, 5)

            return render(request, 'myauth/profile.html', context=liked_context | {'user': user})
        else:
            return redirect('profile-token')
    else:
        if user.userprofile.hidden:
            return HttpResponse("User is hidden")
        else:
            token = user.userprofile.get_token()
            client = Client(token).init()
            liked_context = create_like_playlist(client, 5)

            return render(request, 'myauth/profile.html', context=liked_context | {'user': user})

def redirect_to_profile_view(request):
    return redirect('profile', request.user.username)

def logout_view(request):
    logout(request)
    return redirect('main-page')


def login_view(request):
    form = LoginForm(request.POST)
    if form.is_valid():
        user = authenticate(
            request,
            username=form.cleaned_data['username'],
            password=form.cleaned_data['password']
        )
        if user:
            login(request, user)
            return redirect('profile-token')
    return render(request, 'myauth/Auth.html', {
        'error': 'Email or password is incorrect',
        'form1': LoginForm(),
        'form2': RegisterForm()
    })


def register_view(request):
    form = RegisterForm(request.POST)
    if form.is_valid():
        username = form.cleaned_data['username']
        email = form.cleaned_data['email']
        password = form.cleaned_data['password']

        if User.objects.filter(username=username).exists():
            return render(request, 'myauth/Auth.html', {
                'error': 'Username already exists',
                'form1': LoginForm(),
                'form2': RegisterForm()
            })

        user = User.objects.create_user(username=username, email=email, password=password)
        login(request, user)
        return redirect('profile-token')

    return render(request, 'myauth/Auth.html', {
        'error': 'Error',
        'form1': LoginForm(),
        'form2': RegisterForm()
    })


def profile_edit_view(request):
    if request.method == 'GET':
        form = UserForm()

        form.fields['username'].widget.attrs['placeholder'] = request.user.username
        form.fields['email'].widget.attrs['placeholder'] = request.user.email
        form.fields['bio'].widget.attrs['placeholder'] = request.user.userprofile.bio
        if request.user.userprofile.hidden == True:
            form.fields['hidden'].widget.attrs['checked'] = 'checked'

        return render(request, 'myauth/profile-edit.html', {'form': form})

    elif request.method == 'POST':
        form = UserForm(request.POST, request.FILES)

        form.fields['username'].widget.attrs['placeholder'] = request.user.username
        form.fields['email'].widget.attrs['placeholder'] = request.user.email
        form.fields['bio'].widget.attrs['placeholder'] = request.user.userprofile.bio
        if request.user.userprofile.hidden == True:
            form.fields['hidden'].widget.attrs['checked'] = 'checked'

        user = request.user
        if form.is_valid():
            avatar = form.cleaned_data.get('avatar')
            username = form.cleaned_data.get('username')
            email = form.cleaned_data.get('email')
            bio = form.cleaned_data.get('bio')
            hidden = form.cleaned_data.get('hidden')

            if username:
                # Проверяем, что username не занят другим пользователем
                if User.objects.filter(username=username).exclude(pk=user.pk).exists():
                    return render(request, 'myauth/profile-edit.html', {'form': form, 'error': True})
                user.username = username

            if email:
                user.email = email

            if bio:
                user.userprofile.bio = bio

            # ВАЖНО: Сохраняем аватар
            if avatar:
                print("------------")
                user.userprofile.avatar = avatar

            user.userprofile.hidden = hidden
            user.save()
            user.userprofile.save()

            return redirect('profile', username=user.username)

        return render(request, 'myauth/profile-edit.html', {'form': form, 'error': True})

def create_like_playlist(client, count):
    tracks = list(client.users_likes_tracks()[:count])
    liked_track_list = []
    for track_obj in tracks[:5]:  # Get first 5 liked tracks
        id = track_obj.id
        track = track_obj.fetch_track()
        title = track.title
        artist = " " + ', '.join(artist.name for artist in track.artists)
        url = "https://music.yandex.ru/track/" + str(id)

        img = None
        if track.cover_uri:
            img = f"https://{track.cover_uri.replace('%%', '200x200')}"

        liked_track_list.append({
            'liked_title': title,
            'liked_artist': artist,
            'liked_image': img,
            'liked_url': url
        })
    context = {"liked_track_list": liked_track_list}
    return context

myauth/templates/myauth/Auth.html
{% extends 'base.html' %}
{% load static %}

{% block Title %}
    Login
{% endblock %}
{% block css %}
    <link rel="stylesheet" href="{% static 'myauth/css/login.css' %}">
{% endblock %}
{% block content %}
    <div class="login-box" id="login-box">
        <h1>Login</h1>
        <form method="post" autocomplete="off">
            {% csrf_token %}
            {{ form1.username }}
            {{ form1.password }}
            <div class="options">
                <div>
                     <input type="checkbox">
                    <span class="text">Remember me</span>
                </div>
                <a href="#">Forgot Password?</a>
            </div>
            <button type="submit" name="action" value="login">Login</button>
            {% if error %}
                <div style="color: #ffd700; font-size: 20px">
                    {{ error }}
                </div>
            {% endif %}
            <a href="#" class="register">
                <p class="parag">Don't have an account? Register</p>
            </a>
        </form>
    </div>

    {# REGISTER #}
    <div class="register-box" id="register-box">
        <h1>Register</h1>
        <form method="post" autocomplete="off">
            {% csrf_token %}
            {{ form2.username }}
            {{ form2.email }}
            {{ form2.password }}
            <button type="submit" name="action" value="register">Register</button>
            {% if error %}
                <div style="color: #ffd700; font-size: 20px">
                    {{ error }}
                </div>
            {% endif %}
            <a href="#" class="register">
                <p class="parag">Have an account? Login</p>
            </a>
        </form>
    </div>
 <script src="{% static 'myauth/js/script.js' %}"></script>
{% endblock %}

myauth/templates/myauth/profile-edit.html
{% extends 'base.html' %}


{% load static %}

{% block Title %}
    edit
{% endblock %}

{% block css %}
    <link rel="stylesheet" href="{% static 'myauth/css/profile-edit.css' %}">
{% endblock %}

{% block content %}
    <div class="container">
        <div class="header">
            <h1>Edit Profile</h1>
        </div>
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
        <div class="avatar-upload">
                <label for="id_avatar" class="avatar-preview" id="avatarPreview">
                {% if request.user.userprofile.avatar %}
                    <img src="{{ request.user.userprofile.avatar.url }}" alt="Avatar">
                {% endif %}
                {{ form.avatar }}
        </div>

        <div class="form-section">

            <div class="form-group">
                <label for="username">Username</label>
                {{ form.username }}
            </div>

            <div class="form-group">
                <label for="email">Email</label>
                {{ form.email }}
            </div>

            <div class="form-group">
                <label for="bio">Bio</label>
                {{ form.bio }}
            </div>
            <div>
                <label for="hidden">Hide profile?</label>
                {{ form.hidden }}
            </div>
        <div class="button-group">
            <button class="btn btn-secondary">Отмена</button>
            <button class="btn btn-primary">Сохранить изменения</button>
        </div>
    </div>
        </form>
    {% if error %}
    	<div> ERROR</div>
    {% endif %}
{% endblock %}

myauth/templates/myauth/profile-token.html
{% extends 'base.html' %}
{% load static %}

{% block Title %}
    Token
{% endblock %}

{% block css %}
    <link rel="stylesheet" href="{% static 'myauth/css/profile-token.css' %}">
{% endblock %}

{% block content %}
    <div class="profile-conteiner">
        <img src="{% static 'myauth/img/images.png' %}" alt="">
        <h1 class="title">Last step send your token</h1>
        <form method="post">
            {% csrf_token %}
            {{ form.token }}
            <button type="submit">Send</button>
        </form>
        {% if error %}
            <h1>Error!!! try one more</h1>
        {% endif %}
    </div>
{% endblock %}

myauth/templates/myauth/profile.html
{% extends 'base.html' %}


{% load static %}

{% block Title %}
    Profile
{% endblock %}

{% block css %}
    <link rel="stylesheet" href="{% static 'myauth/css/profile.css' %}">
{% endblock %}

{% block content %}
    <div class="profile-conteiner">
        <div class="profile-header-container">
            {% if user.userprofile.avatar %}
                <img src="{{ user.userprofile.avatar.url }}" width="200" height="200" alt="{{ user.username }}">
            {% else %}
                <img src="{% static 'myauth/img/images.png' %}" alt="Default avatar">
            {% endif %}
            <h1>Check your stats in Yandex Music</h1>
        </div>
    <div class="username-text" >{{ user.username }}</div>
    {% if request.user.username == user.username%}
    	<div class="edit-button"><a href="{% url 'profile-edit'%}">Edit profile</a></div>
    {% endif %}


    <div class="liked-track-container">Your last liked tracks</div>
    <div class="tracks-container">
        {% for i in liked_track_list %}
            <a href="{{ i.liked_url }}" target="_blank">
                <div class="track-card">
                    <img src="{{ i.liked_image }}">
                    <p class="mar">{{ i.liked_title }}</p>
                    <p class="mar">{{ i.liked_artist }}</p>
                </div>
            </a>
        {% endfor %}
    </div>
    </div>



{% endblock %}